isoform_diff_data <- diffData(isoforms(Grant_data), 'control_proliferative', 'case_proliferative')
sig_isoform_data <- subset(isoform_diff_data, (significant == 'yes'))
nrow(sig_isoform_data)
tss_diff_data <- diffData(TSS(Grant_data), 'control_proliferative', 'case_proliferative')
sig_tss_data <- subset(tss_diff_data, (significant == 'yes'))
nrow(sig_tss_data)
cds_diff_data <- diffData(CDS(Grant_data), 'control_proliferative', 'case_proliferative')
sig_cds_data <- subset(cds_diff_data, (significant == 'yes'))
nrow(sig_cds_data)
promoter_diff_data <- distValues(promoters(Grant_data))
sig_promoter_data <- subset(promoter_diff_data, (significant == 'yes'))
nrow(sig_promoter_data)
splicing_diff_data <- distValues(splicing(Grant_data))
sig_splicing_data <- subset(splicing_diff_data, (significant == 'yes'))
nrow(sig_splicing_data)
relCDS_diff_data <- distValues(relCDS(Grant_data))
sig_relCDS_data <- subset(relCDS_diff_data, (significant == 'yes'))
nrow(sig_relCDS_data)

gene_diff_data <- diffData(genes(Grant_data))
sig_gene_data <- subset(gene_diff_data, (significant == 'yes'))
write.table(sig_gene_data, 'diff_genes.txt', sep='\t', row.names = F, col.names = T, quote = F)
